### ISSUE TITLE
View moves downwards when applying basic shimmer

### ISSUE THREAD

**Issue by d9rad** [markiv/SwiftUI-Shimmer#14]
I noticed since the last update that using `.shimmering()` on a view will cause it to move.

This is the code using `.shimmering`:

``` swift
Text("Test shimmer")
    .shimmering()
```

The result:

https://github.com/markiv/SwiftUI-Shimmer/assets/3265288/b9ab1b64-19e4-47e5-bd75-90625e9c6a23

When using 1.3.0 the view stays in place and behaves as expected.

This is using Xcode 14.3 with iPhone 14 Pro (16.4) simulator

**Comment by markiv** [comment]
What about the surrounding code? How is that view being laid out on the screen? Can you provide code to reproduce the issue?

**Comment by d9rad** [comment]
It seems to happen when using `NavigationView` and `NavigationLink` as follows:

```swift
NavigationView {
    NavigationLink("Shimmer test") {
        Text("Foobar")
            .shimmering()
    }
}
```

The same also happens when placing the `Text` inside its own view.

The weird thing is that it doesn't happen when using `NavigationStack`. I guess it's not really an issue for anyone targeting iOS 16+ 🤔

**Comment by keithburgoyne** [comment]
We are also seeing this issue. We currently target iOS 14.+.

**Comment by gesabo** [comment]
Experiencing this as well in iOS 16.

**Comment by gesabo** [comment]
> The issue is with the body, replacing the withAnimation of initialState with .animate or using async dispatchqueue worked for me https://www.hackingwithswift.com/forums/swiftui/gradient-animation-inside-of-navigation-view/13356

@BolzanNicolas do you mean creating your own fork to fix the issue?

**Comment by BolzanNicolas** [comment]
> > The issue is with the body, replacing the withAnimation of initialState with .animate or using async dispatchqueue worked for me https://www.hackingwithswift.com/forums/swiftui/gradient-animation-inside-of-navigation-view/13356
> 
> @BolzanNicolas do you mean creating your own fork to fix the issue?

Yes, modifying Shimmer's body directly like this or async dispatch

```
public func body(content: Content) -> some View {
        content
            .mask(LinearGradient(gradient: gradient, startPoint: startPoint, endPoint: endPoint))
            .animation(animation, value: isInitialState)
            .onAppear {
                isInitialState = false
            }
    }
```

**Comment by gesabo** [comment]
Thanks so much @BolzanNicolas !

**Comment by gesabo** [comment]
Unfortunately iOS 17.1 beta seems to cause the same visual bug even when using @BolzanNicolas's solution.

**Comment by gesabo** [comment]
> Unfortunately iOS 17.1 beta seems to cause the same visual bug even when using @BolzanNicolas's solution.

I was able to solve it using [this](https://github.com/propnex/SwiftUI-Shimmer/commit/e002ce8e68c475f9dfc85d3187545e129e68be4d) solution

**Comment by markiv** [comment]
Fixed in 1.4.1. Thanks for the inputs!

**Comment by roger-smith** [comment]
Hi @markiv, could you tag the new release for 1.4.1 please?

**Comment by emilloohoo** [comment]
@markiv can you please tag 1.4.1? i would love to do this vs upgrade to ios 16

**Comment by iamnanyi** [comment]
This problem still occurs in version 1.5.1, Xcode 16.1, iOS 17.3
